/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginpage1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class CarInfo extends javax.swing.JFrame {

    /**
     * Creates new form CarInfo
     */
    public String type;
    String car_id;
    
    public CarInfo() {
        initComponents();
        type_combo_box();
        table_show_car();
        
    }
    
    private void type_combo_box(){
            try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=Car_Rental_System1", "sa", "123456");
            
            Statement pst = connection.createStatement();
            //ResultSet rs = pst.executeQuery();
            String query = "SELECT DISTINCT Type FROM Car_Info1 ";
            ResultSet rs = pst.executeQuery(query);
            while(rs.next()){
                type_combo1.addItem(rs.getString("Type"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void table_show_car(){
            try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=Car_Rental_System1", "sa", "123456");
             
            String query = "SELECT Type,Model,Color FROM Car_Info1 ";
            PreparedStatement pst = connection.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
            while(rs.next()){
                
                String type = rs.getString("Type");
                String model = rs.getString("Model");
                String color = rs.getString("Color");
                
                String tbData[] = {type,model,color};
                DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
                tblModel.addRow(tbData);
            }
                //System.out.println(type);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        color_combo1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        type_combo1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        model_combo1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        available_field1 = new javax.swing.JTextField();
        car_id_field = new javax.swing.JTextField();
        Ok = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setPreferredSize(new java.awt.Dimension(810, 553));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Impact", 0, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Car Info");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 320, 50));

        jLabel3.setFont(new java.awt.Font("Impact", 0, 35)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Color");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 90, 40));

        color_combo1.setFont(new java.awt.Font("Impact", 0, 25)); // NOI18N
        color_combo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                color_combo1ActionPerformed(evt);
            }
        });
        jPanel2.add(color_combo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 230, 40));

        jLabel4.setFont(new java.awt.Font("Impact", 0, 35)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Type");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 80, 40));

        type_combo1.setFont(new java.awt.Font("Impact", 0, 25)); // NOI18N
        type_combo1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                type_combo1ItemStateChanged(evt);
            }
        });
        jPanel2.add(type_combo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 230, 40));

        jLabel5.setFont(new java.awt.Font("Impact", 0, 35)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Model");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 90, 40));

        model_combo1.setFont(new java.awt.Font("Impact", 0, 25)); // NOI18N
        model_combo1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                model_combo1ItemStateChanged(evt);
            }
        });
        jPanel2.add(model_combo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 230, 40));

        jLabel6.setFont(new java.awt.Font("Impact", 0, 35)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Available");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, -1, -1));

        jLabel7.setFont(new java.awt.Font("Impact", 0, 35)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Car Id");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));
        jPanel2.add(available_field1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 130, 30));
        jPanel2.add(car_id_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 100, 30));

        Ok.setBackground(new java.awt.Color(255, 255, 255));
        Ok.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        Ok.setForeground(new java.awt.Color(51, 0, 0));
        Ok.setText("OK");
        Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkActionPerformed(evt);
            }
        });
        jPanel2.add(Ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 500, 80, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Type", "Model", "Color"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 390, 440));

        Back.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        Back.setForeground(new java.awt.Color(51, 0, 0));
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        jPanel2.add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 881, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void color_combo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_color_combo1ActionPerformed
        // TODO add your handling code here:
        try{
           Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=Car_Rental_System1", "sa", "123456");
            Statement pst = connection.createStatement();
            String query1 = "SELECT Car_Id FROM Car_Info1 WHERE Type='"+type_combo1.getSelectedItem()+"' AND Model='"+model_combo1.getSelectedItem()+"' AND Color='"+color_combo1.getSelectedItem()+"'";
            ResultSet rs = pst.executeQuery(query1);
            while(rs.next()){
                car_id_field.setText(rs.getString("Car_Id"));
                
                //car_id = car_id_field.getText();
                
            }
            //int i = Integer.parseInt(available_field.getText());
            String query2 = "SELECT Available FROM Available WHERE Available_Id='"+car_id_field.getText()+"'";
            //String query2 = "SELECT Available FROM Available WHERE Available_Id = i ";
            ResultSet rs1 = pst.executeQuery(query2);
            while(rs1.next()){
                available_field1.setText(rs1.getString("Available"));
                if(available_field1.getText().equals("Yes"))
                {
                    Ok.setEnabled(true);
                }else{
                    Ok.setEnabled(false);
                }
 
            }
            
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_color_combo1ActionPerformed

    private void type_combo1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_type_combo1ItemStateChanged
        // TODO add your handling code here:
         try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=Car_Rental_System1", "sa", "123456");
            
            Statement pst = connection.createStatement();
            //ResultSet rs = pst.executeQuery();
            String query = "SELECT DISTINCT Model FROM Car_Info1 WHERE Type='"+type_combo1.getSelectedItem()+"'";
            ResultSet rs = pst.executeQuery(query);
            model_combo1.removeAllItems();
            while(rs.next()){
                model_combo1.addItem(rs.getString("Model"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_type_combo1ItemStateChanged

    private void model_combo1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_model_combo1ItemStateChanged
        // TODO add your handling code here:
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=Car_Rental_System1", "sa", "123456");
            
            Statement pst = connection.createStatement();
            //ResultSet rs = pst.executeQuery();
            String query = "SELECT Color FROM Car_Info1 WHERE Model='"+model_combo1.getSelectedItem()+"'";
            ResultSet rs = pst.executeQuery(query);
            color_combo1.removeAllItems();
            while(rs.next()){
                color_combo1.addItem(rs.getString("Color"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_model_combo1ItemStateChanged

    private void OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=Car_Rental_System1", "sa", "123456");
            //Statement pst = connection.createStatement();
            //String query = "INSERT INTO Available (Available) VALUES('No') WHERE Available_Id='"+available_field.getText()+"'";
            String query = "UPDATE Available SET Available = 'No' WHERE Available_Id='"+car_id_field.getText()+"'";
            PreparedStatement pst = connection.prepareStatement(query);
            
            pst.executeUpdate();
            //pst.executeQuery(query);
            /*while(rs.next()){
                A_field.setText(rs.getString("Available"));
            }*/
            
            JOptionPane.showMessageDialog(null, "Insert successful");
            
            
            //new Customer(car_id).setVisible(true);
            
            Customer page = new Customer();
            page.setVisible(true);
            setVisible(false);
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_OkActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
         Dashboard page = new Dashboard();
            page.setVisible(true);
            setVisible(false);
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Ok;
    private javax.swing.JTextField available_field1;
    private javax.swing.JTextField car_id_field;
    private javax.swing.JComboBox<String> color_combo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> model_combo1;
    private javax.swing.JComboBox<String> type_combo1;
    // End of variables declaration//GEN-END:variables
}
