/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginpage1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Delete extends javax.swing.JFrame {

    /**
     * Creates new form Delete
     */
    public Delete() {
        initComponents();
        show_data();
    }
    
    private void show_data(){
        try {
             Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
             Connection connection = DriverManager.getConnection(
                       "jdbc:sqlserver://localhost:1433;databaseName=Car_Rental_System1", "sa", "123456");
            //String query = "SELECT Customer_Id, Customer_Name, Contact_no FROM Customer2";
            String query = "SELECT c.Customer_Id, Customer_Name, c.Contact_no, p.Payment_Id FROM Customer2 as c Full JOIN Payment as p ON c.Customer_Id = p.Customer_Id";
            PreparedStatement pst = connection.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
            while(rs.next()){
                String customerID = String.valueOf(rs.getInt("Customer_Id"));
                String customerName = rs.getString("Customer_Name");                   
                String con_no = rs.getString("Contact_no");
                String Pay_ID = String.valueOf(rs.getInt("Payment_Id"));
                //String d_lisence = rs.getString("Driving_Lisense");
                //String address = rs.getString("Address");
                String tbData[] = {customerID,customerName,con_no,Pay_ID};
                DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();

                tblModel.addRow(tbData);
            }
            
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Phone_no = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        C_id = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        Delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(35, 81, 66));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer Id", " Name", "Phone No", "Pay Id"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 810, 180));

        Back.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        Back.setForeground(new java.awt.Color(0, 102, 102));
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        jPanel1.add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, -1));

        jLabel1.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Contact No");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 130, 40));

        Phone_no.setBackground(new java.awt.Color(35, 81, 66));
        Phone_no.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        Phone_no.setForeground(new java.awt.Color(255, 255, 255));
        Phone_no.setBorder(null);
        jPanel1.add(Phone_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 150, 40));

        jLabel2.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Customer Id");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 130, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 160, 10));

        C_id.setBackground(new java.awt.Color(35, 81, 66));
        C_id.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        C_id.setForeground(new java.awt.Color(255, 255, 255));
        C_id.setBorder(null);
        jPanel1.add(C_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 150, 40));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 150, 10));

        Delete.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        Delete.setForeground(new java.awt.Color(0, 102, 102));
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        jPanel1.add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
         Dashboard page = new Dashboard();
            page.setVisible(true);
            setVisible(false);
        
    }//GEN-LAST:event_BackActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
          String id = C_id.getText();
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
             Connection connection = DriverManager.getConnection(
                       "jdbc:sqlserver://localhost:1433;databaseName=Car_Rental_System1", "sa", "123456");
             
             String q4 = "Update Available Set Available = 'Yes' where Car_Id =(Select Car_Id from Customer2 where Customer_Id ='"+C_id.getText()+"' )";
             PreparedStatement pst3 = connection.prepareStatement(q4);
             pst3.executeUpdate(); 

             String q2 = "DELETE FROM Payment WHERE Customer_Id= ANY (SELECT Customer_Id FROM Customer2 WHERE Customer_Id='"+C_id.getText()+"')";
             //System.out.println("AAAAAAAAAAA");
             PreparedStatement pst1 = connection.prepareStatement(q2);
             pst1.executeUpdate();
             
             String query= "Delete from Customer2 where Customer_Id='"+id+"'";
             PreparedStatement pst = connection.prepareStatement(query);
             pst.executeUpdate();
             
             
             String q3 = "Delete From Booking1 Where Contact_no='"+Phone_no.getText()+"'";
             PreparedStatement pst2 = connection.prepareStatement(q3);
             pst2.executeUpdate();
               
             
             JOptionPane.showMessageDialog(null, "Delete successful");
             
             Delete page = new Delete();
             page.setVisible(true);
             setVisible(false);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_DeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Delete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JTextField C_id;
    private javax.swing.JButton Delete;
    private javax.swing.JTextField Phone_no;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
