/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginpage1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Ripon
 */
public class Payment extends javax.swing.JFrame {

    /**
     * Creates new form Payment
     */
    public Payment() {
        initComponents();
        customer_id();
        status_bar();
    }
    
    private void status_bar(){
        status.addItem("Due");
        status.addItem("Complete");
    }
    
     private void customer_id(){
        //System.out.println(phone);
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=Car_Rental_System1", "sa", "123456");
            String q1 = "Select MAX(Customer_Id) as m From Customer2";
            Statement statement = connection.createStatement();
            ResultSet rs = statement.executeQuery(q1);
            while(rs.next()){
                CustomerId.setText(rs.getString("m"));
            }
            
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CustomerId = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        TotalAmount = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        OK = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Due = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        status = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        Back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(168, 138, 138));
        setMinimumSize(new java.awt.Dimension(850, 620));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(64, 108, 108));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(109, 85, 85));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("F:\\3.1\\Database\\PROJECT 3.1\\JAVA\\loginPage1\\src\\loginpage1\\payment.png")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 260, 270));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 10));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 10, 440));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 340, 450));

        jLabel2.setFont(new java.awt.Font("Impact", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Payment Info");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 270, 50));

        jLabel3.setFont(new java.awt.Font("Impact", 0, 25)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Status                 :");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, 160, 30));

        jLabel4.setFont(new java.awt.Font("Impact", 0, 25)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Total Amount :");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 160, 30));

        CustomerId.setBackground(new java.awt.Color(64, 108, 108));
        CustomerId.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        CustomerId.setForeground(new java.awt.Color(255, 255, 255));
        CustomerId.setBorder(null);
        jPanel5.add(CustomerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 350, 260, 30));
        jPanel5.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, 260, 10));

        TotalAmount.setBackground(new java.awt.Color(64, 108, 108));
        TotalAmount.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        TotalAmount.setForeground(new java.awt.Color(255, 255, 255));
        TotalAmount.setBorder(null);
        jPanel5.add(TotalAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 260, 30));
        jPanel5.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 260, 20));

        OK.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        OK.setText("OK");
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });
        jPanel5.add(OK, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 520, 70, 30));

        jLabel5.setFont(new java.awt.Font("Impact", 0, 25)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Due                        :");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 160, 30));

        Due.setBackground(new java.awt.Color(64, 108, 108));
        Due.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        Due.setForeground(new java.awt.Color(255, 255, 255));
        Due.setBorder(null);
        jPanel5.add(Due, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 260, 30));
        jPanel5.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 260, 10));

        status.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });
        jPanel5.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, 160, 40));

        jLabel6.setFont(new java.awt.Font("Impact", 0, 25)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Customer Id   :");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 160, 30));

        Back.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        jPanel5.add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 520, -1, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
        // TODO add your handling code here:
         try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=Car_Rental_System1", "sa", "123456");
            
            String query = "insert into Payment(TotalAmount, Due, Customer_id, Status) values (?,?,?,?)";
            PreparedStatement pst = connection.prepareStatement(query);
            pst.setString(1,TotalAmount.getText());
            pst.setString(2,Due.getText());
            pst.setString(3,CustomerId.getText());
            
           
            
            String value = status.getSelectedItem().toString();
            pst.setString(4, value);
            
            
             pst.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Insert successful");
            /*String duration = "Select DATEDIFF(DAY, Return_Date , Starting_Date) from Booking";
            PreparedStatement pst1 = connection.prepareStatement(duration);
            pst1*/
            Dashboard page = new Dashboard();
            page.setVisible(true);
            setVisible(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_OKActionPerformed

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        // TODO add your handling code here:
        /*try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=Car_Rental_System1", "sa", "123456");
            
             ResultSet rs;
             
             String value = status.getSelectedItem().toString();
             if(value.equals("Due")){
                 String query = "insert into Payment(Status) values ('Due')";
                 PreparedStatement pst = connection.prepareStatement(query);
                 pst.executeUpdate();
             }
             else if(value.equals("Complete")){
                 String query = "insert into Payment(Status) values ('Complete')";
                 PreparedStatement pst = connection.prepareStatement(query);
                 pst.executeUpdate();
             }
                 
            
        } catch (Exception e) {
        }*/
    }//GEN-LAST:event_statusActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        Dashboard page = new Dashboard();
        page.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JTextField CustomerId;
    private javax.swing.JTextField Due;
    private javax.swing.JButton OK;
    private javax.swing.JTextField TotalAmount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JComboBox<String> status;
    // End of variables declaration//GEN-END:variables
}
