/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginpage1;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Return_car extends javax.swing.JFrame {

    /**
     * Creates new form Return_car
     */
    String contact ;
     String ret;
     int fine;
    public Return_car() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Time = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        Contact_no = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        txt_fine = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        customer_id = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        Car_id = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ok = new javax.swing.JButton();
        Current_date = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(157, 99, 101));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Car Return Info");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 350, 70));

        jLabel3.setFont(new java.awt.Font("Impact", 0, 25)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fine                         :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 160, 30));

        jLabel4.setFont(new java.awt.Font("Impact", 0, 25)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Car Id                     :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 160, 30));

        jLabel5.setFont(new java.awt.Font("Impact", 0, 25)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Date                        :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 160, 30));

        jLabel6.setFont(new java.awt.Font("Impact", 0, 25)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Time Elapsed  :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 150, 30));

        jLabel7.setFont(new java.awt.Font("Impact", 0, 25)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Phone No            :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 160, 30));

        jLabel8.setFont(new java.awt.Font("Impact", 0, 25)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Customer Id     :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 160, 30));

        Time.setBackground(new java.awt.Color(157, 99, 101));
        Time.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        Time.setForeground(new java.awt.Color(255, 255, 255));
        Time.setBorder(null);
        jPanel1.add(Time, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 200, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 210, 20));

        Contact_no.setBackground(new java.awt.Color(157, 99, 101));
        Contact_no.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        Contact_no.setForeground(new java.awt.Color(255, 255, 255));
        Contact_no.setBorder(null);
        Contact_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Contact_noActionPerformed(evt);
            }
        });
        Contact_no.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Contact_noKeyPressed(evt);
            }
        });
        jPanel1.add(Contact_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 200, 30));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 210, 20));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 210, 10));

        txt_fine.setBackground(new java.awt.Color(157, 99, 101));
        txt_fine.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        txt_fine.setForeground(new java.awt.Color(255, 255, 255));
        txt_fine.setBorder(null);
        jPanel1.add(txt_fine, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 200, 30));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 210, 20));

        customer_id.setBackground(new java.awt.Color(157, 99, 101));
        customer_id.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        customer_id.setForeground(new java.awt.Color(255, 255, 255));
        customer_id.setBorder(null);
        customer_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                customer_idKeyPressed(evt);
            }
        });
        jPanel1.add(customer_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 200, 30));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 210, 20));

        Car_id.setBackground(new java.awt.Color(157, 99, 101));
        Car_id.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        Car_id.setForeground(new java.awt.Color(255, 255, 255));
        Car_id.setBorder(null);
        Car_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Car_idActionPerformed(evt);
            }
        });
        jPanel1.add(Car_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 200, 30));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 500, 210, 20));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Total Payment", "Due", "Total(with Fine)", "Due(with Fine)"
            }
        ));
        jTable2.setGridColor(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(jTable2);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, -1, 90));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer Id", "Customer Name", "Car Id", "Return Date"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(51, 51, 51));
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, -1, 90));

        ok.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        ok.setText("Ok");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        jPanel1.add(ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 540, 70, 40));

        Current_date.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(Current_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 210, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 884, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Contact_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Contact_noActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=Car_Rental_System1", "sa", "123456");
            String query = "SELECT Customer_Id, Customer_Name, Car_Id, Booking1.Return_Date FROM Customer2 INNER JOIN Booking1 on Customer2.Contact_no='"+Contact_no.getText()+"'AND Booking1.Contact_no ='"+Contact_no.getText()+"'";
             
            contact = Contact_no.getText();
            Statement statement = connection.createStatement();
            ResultSet rs = statement
                    .executeQuery(query);
            //ResultSet rs = pst.executeQuery(query);
            //UserAccount UserAcc = null;
            
             while(rs.next()) {

                String customerID = String.valueOf(rs.getInt("Customer_Id"));
                String customerName = rs.getString("Customer_Name");
                String car_id = String.valueOf(rs.getInt("Car_Id"));
                String return_date = rs.getString("Return_Date");
             
                String tbData[] = {customerID,customerName,car_id,return_date};
                DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
                tblModel.addRow(tbData);
                
                //return_date1.setText(rs.getString("Return_date"));
                //ret = return_date1.getText();
                }
             
          /*   String query1 = "Select Return_Date, DATEDIFF(NOW(),Return_Date) as elap From Booking1 WHERE Contact_no='"+Contact_no.getText()+"'"; 
            //System.out.println(ret);
            PreparedStatement pst = connection.prepareStatement(query1);
             ResultSet rs1 = pst.executeQuery(query1);
            while(rs.next()){
                String elp = rs1.getString("elap");
                //int e = Integer.parseInt(elp);
                Time.setText("elp");
            }*/

            connection.close();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_Contact_noActionPerformed

    private void Car_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Car_idActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=Car_Rental_System1", "sa", "123456");
            
            String query = "UPDATE Available SET Available = 'Yes' WHERE Available_Id='"+Car_id.getText()+"'";
            PreparedStatement pst = connection.prepareStatement(query);
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Update successful");
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_Car_idActionPerformed

    private void Contact_noKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Contact_noKeyPressed
        // TODO add your handling code here:
                
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                Connection connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=Car_Rental_System1", "sa", "123456");
               // String query = "SELECT Customer_Id, Customer_Name, Car_Id, Booking1.Return_Date FROM Customer2 INNER JOIN Booking1 on Customer2.Contact_no=? AND Booking1.Contact_no=? ";
                String query1 = "Select Return_Date, DATEDIFF(Day, Return_Date, '"+((JTextField)Current_date.getDateEditor().getUiComponent()).getText()+"') as elap From Booking1 WHERE Contact_no=?" ;
                PreparedStatement pst = connection.prepareStatement(query1);
                pst.setString(1,Contact_no.getText());
                ResultSet rs = pst.executeQuery();
                while(rs.next() ){
                    //JOptionPane.showMessageDialog(null, "Error");
                
                    String elp = rs.getString("elap");
                    int e = Integer.parseInt(elp);
                    Time.setText(elp);
                    if(e > 0){
                        fine = e*100;
                        txt_fine.setText(String.valueOf(fine));
                    }else{
                       txt_fine.setText(String.valueOf(fine)); 
                    }
                }
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_Contact_noKeyPressed

    private void customer_idKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_customer_idKeyPressed
        // TODO add your handling code here:
        try {
            if(evt.getKeyCode() == KeyEvent.VK_ENTER){
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                Connection connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=Car_Rental_System1", "sa", "123456");
                String query = "Select TotalAmount, Due, TotalAmount+'"+fine+"' as t, Due+'"+fine+"' as d from Payment WHERE Customer_Id='"+customer_id.getText()+"'";
                Statement statement = connection.createStatement();
                ResultSet rs = statement
                    .executeQuery(query);
                
                while(rs.next()) {

                String total_am = String.valueOf(rs.getInt("TotalAmount"));
                String due = String.valueOf(rs.getInt("Due"));
                String total_fine = String.valueOf(rs.getInt("t"));
                String total_due = String.valueOf(rs.getInt("d"));
             
                String tbData[] = {total_am,due,total_fine,total_due};
                DefaultTableModel tblModel = (DefaultTableModel)jTable2.getModel();
                tblModel.addRow(tbData);
                
                //return_date1.setText(rs.getString("Return_date"));
                //ret = return_date1.getText();
                }
                
                String q2 = "UPDATE Payment SET Fine='"+fine+"', Status = 'Complete', Due = '"+0+"' Where Customer_Id='"+customer_id.getText()+"'";
                PreparedStatement pst = connection.prepareStatement(q2);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Update successful");
            }
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_customer_idKeyPressed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        // TODO add your handling code here:
        Dashboard page = new Dashboard();
        page.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_okActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Return_car.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Return_car.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Return_car.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Return_car.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Return_car().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Car_id;
    private javax.swing.JTextField Contact_no;
    private com.toedter.calendar.JDateChooser Current_date;
    private javax.swing.JTextField Time;
    private javax.swing.JTextField customer_id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton ok;
    private javax.swing.JTextField txt_fine;
    // End of variables declaration//GEN-END:variables
}
