/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginpage1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Revenue extends javax.swing.JFrame {

    /**
     * Creates new form Revenue
     */
    public Revenue() {
        initComponents();
        show_data();
    }
    
    private void show_data(){
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
             Connection connection = DriverManager.getConnection(
                       "jdbc:sqlserver://localhost:1433;databaseName=Car_Rental_System1", "sa", "123456");
             String query = "Select Customer_Id, Contact_no from Customer2 Where Customer_Id = Any(Select p.Customer_Id from Payment as p Where Status = 'Complete') ";
             String query1 = "Select Payment_Id, TotalAmount, Fine, TotalAmount+Fine as tf from Payment as p  inner join Customer2 as c ON p.Customer_Id = c.Customer_Id where Status = 'Complete'";
             
             PreparedStatement pst = connection.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
            
            PreparedStatement pst1 = connection.prepareStatement(query1);
            ResultSet rs1 = pst1.executeQuery();
            
            while(rs.next() && rs1.next()){
                String customerID = String.valueOf(rs.getInt("Customer_Id"));                   
                String con_no = rs.getString("Contact_no");
                String pay_id = String.valueOf(rs1.getInt("Payment_Id"));
                String ta = String.valueOf(rs1.getInt("TotalAmount"));
                String fine = String.valueOf(rs1.getInt("Fine"));
                String tf = String.valueOf(rs1.getInt("tf"));
                String tbData[] = {customerID,con_no,pay_id,ta,fine,tf};
                DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();

                tblModel.addRow(tbData);
                
                
            }
            String q2 = "Select Sum(TotalAmount+Fine) as tf from Payment";
            PreparedStatement pst2 = connection.prepareStatement(q2);
            ResultSet rs2 = pst2.executeQuery();
            while(rs2.next()){
                tot_fine.setText(rs2.getString("tf"));
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        tot_fine = new javax.swing.JTextField();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(48, 96, 143));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer Id", "Contact No", "Pay Id", "Total Payment", "Fine", "Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 830, 150));

        jLabel1.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Total Revenue");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 160, 50));

        tot_fine.setBackground(new java.awt.Color(48, 96, 143));
        tot_fine.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        tot_fine.setForeground(new java.awt.Color(255, 255, 255));
        tot_fine.setBorder(null);
        tot_fine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tot_fineActionPerformed(evt);
            }
        });
        jPanel1.add(tot_fine, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 240, 160, 50));

        back.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, 90, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tot_fineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tot_fineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tot_fineActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        Dashboard page = new Dashboard();
        page.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Revenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Revenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Revenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Revenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Revenue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tot_fine;
    // End of variables declaration//GEN-END:variables
}
