/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginpage1;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Search extends javax.swing.JFrame {

    /**
     * Creates new form Search
     */
    public Search() {
        initComponents();
        search();
    }

    private void search(){
        search.addItem("Search By Name");
        search.addItem("Search By Phone No");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Show_All_Customer_Info = new javax.swing.JButton();
        search = new javax.swing.JComboBox<>();
        search_bar = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Show_All_Customer_Info.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        Show_All_Customer_Info.setForeground(new java.awt.Color(0, 102, 102));
        Show_All_Customer_Info.setText("Show All Customer Info");
        Show_All_Customer_Info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Show_All_Customer_InfoActionPerformed(evt);
            }
        });
        jPanel1.add(Show_All_Customer_Info, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 270, 40));

        search.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 230, 50));

        search_bar.setBackground(new java.awt.Color(0, 102, 102));
        search_bar.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        search_bar.setForeground(new java.awt.Color(255, 255, 255));
        search_bar.setBorder(null);
        search_bar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                search_barKeyPressed(evt);
            }
        });
        jPanel1.add(search_bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 320, 50));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 320, 20));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer Id", "Name", "Contact No", "Driving Lisence No", "Address"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 830, 300));

        jLabel1.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Search By       :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 160, 50));

        back.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 630, 80, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Show_All_Customer_InfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Show_All_Customer_InfoActionPerformed
        // TODO add your handling code here:
          try {
             Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
             Connection connection = DriverManager.getConnection(
                       "jdbc:sqlserver://localhost:1433;databaseName=Car_Rental_System1", "sa", "123456");
            String query = "SELECT Customer_Id, Customer_Name, Contact_no, Driving_Lisense, Address FROM Customer2";
            PreparedStatement pst = connection.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
            while(rs.next()){
                String customerID = String.valueOf(rs.getInt("Customer_Id"));
                String customerName = rs.getString("Customer_Name");                   
                String con_no = rs.getString("Contact_no");
                String d_lisence = rs.getString("Driving_Lisense");
                String address = rs.getString("Address");
                String tbData[] = {customerID,customerName,con_no,d_lisence,address};
                DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();

                tblModel.addRow(tbData);

            }
        } catch (Exception e) {
        }
         
    }//GEN-LAST:event_Show_All_Customer_InfoActionPerformed

    private void search_barKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_barKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jTable1.setModel(new DefaultTableModel(null, new String[]{"customerID","customerName","d_lisence","con_no","address"}));
            try {
                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    Connection connection = DriverManager.getConnection(
                               "jdbc:sqlserver://localhost:1433;databaseName=Car_Rental_System1", "sa", "123456");
                    ResultSet rs;

                    String value = search.getSelectedItem().toString();
                    if(value.equals("Search By Name")){
                        String query = "SELECT Customer_Id, Customer_Name, Contact_no, Driving_Lisense, Address FROM Customer2 WHERE Customer_Name=?";
                        PreparedStatement pst = connection.prepareStatement(query);
                        pst.setString(1, search_bar.getText());
                        rs = pst.executeQuery();
                        while(rs.next()){
                            String customerID = String.valueOf(rs.getInt("Customer_Id"));
                            String customerName = rs.getString("Customer_Name");                   
                            String con_no = rs.getString("Contact_no");
                            String d_lisence = rs.getString("Driving_Lisense");
                            String address = rs.getString("Address");

                            String tbData[] = {customerID,customerName,d_lisence,con_no,address};
                            DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();

                            tblModel.addRow(tbData);

                        }
                    }
                    else if(value.equals("Search By Phone No")){
                        String query = "SELECT Customer_Id, Customer_Name, Contact_no, Driving_Lisense, Address FROM Customer2 WHERE Contact_no=?";
                        PreparedStatement pst = connection.prepareStatement(query);
                        pst.setString(1, search_bar.getText());
                        rs = pst.executeQuery();
                        while(rs.next()){
                            String customerID = String.valueOf(rs.getInt("Customer_Id"));
                            String customerName = rs.getString("Customer_Name");                   
                            String con_no = rs.getString("Contact_no");
                            String d_lisence = rs.getString("Driving_Lisense");
                            String address = rs.getString("Address");

                            String tbData[] = {customerID,customerName,d_lisence,con_no,address};
                            DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();

                            tblModel.addRow(tbData);

                        }
                    }
                    
                }catch (Exception e) {
                }
        }
    }//GEN-LAST:event_search_barKeyPressed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        Dashboard page = new Dashboard();
        page.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Search().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Show_All_Customer_Info;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> search;
    private javax.swing.JTextField search_bar;
    // End of variables declaration//GEN-END:variables
}
